# Generated by Django 6.0.5 on 2026-05-16 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='notes',
            new_name='general_notes',
        ),
        migrations.RemoveField(
            model_name='menucategory',
            name='name',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='description',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='name',
        ),
        migrations.AddField(
            model_name='menucategory',
            name='name_ar',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='menucategory',
            name='name_en',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='description_ar',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='description_en',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='name_ar',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='name_en',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('DIGITAL', 'Digital (Wallet/InstaPay)')], default='CASH', max_length=10),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='item_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='instapay_id',
            field=models.CharField(blank=True, help_text='InstaPay Username', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='location_radius',
            field=models.PositiveIntegerField(default=50, help_text='Allowed radius in meters'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='wallet_number',
            field=models.CharField(blank=True, help_text='Vodafone Cash / etc', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending (New)'), ('PAYMENT_VERIFY', 'Waiting Payment Verification'), ('COOKING', 'Cooking'), ('READY', 'Ready for Delivery'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=15),
        ),
    ]
