# Generated by Django 6.0.5 on 2026-05-16 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_rename_notes_order_general_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='subscription_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='subscription_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
