# Generated by Django 6.0.5 on 2026-05-16 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_menuitemextra'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='selected_extras',
            field=models.ManyToManyField(blank=True, to='restaurants.menuitemextra'),
        ),
    ]
