# Generated by Django 6.0.5 on 2026-05-17 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_orderitem_selected_extras'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('DIGITAL', 'Digital (Wallet/InstaPay)'), ('CARD', 'Credit/Debit Card (Mock)')], default='CASH', max_length=10),
        ),
    ]
